Initialize components
carloso0114/bookstore-react-redux pull request #1
Opened 2021-08-24 21:38 UTC by carloso0114

In this feature, I was able to recreate the wireframe by building components to look alike it's using real information.

2021-08-24 22:54 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @carloso0114 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
   - The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Categories still under construction:heavy_check_mark:

Changes required :writing_hand:  

      * #### Please check the comments under the review.
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-24 22:54 UTC, Emmyn5600 commented on README.md
> +
- [ ] This is the book store project not Math Magicians project, kindly correct this typo.

2021-08-24 22:54 UTC, Emmyn5600 commented on src/components/addBookForm.js
> +          </span>
- [ ] CreateNewBook
Has a button to submit great job
the button wouldn't add the book yet, this is just a placeholder for now, great work. However, it has to be a button not a text, make it as pointer.
![react3](https://user-images.githubusercontent.com/55635977/130700181-35ca4734-b1b6-4caf-8583-4d39d0716cbd.png)

2021-08-24 22:54 UTC, Emmyn5600 commented on src/redux/books/books.js
> +          <div className="Line-2" />
- [ ] RemoveBook
Has a button for removing books
the button wouldn't remove the books yet, this is just a placeholder for now, great work. However, it has to be a button not a text, make it as pointer.

2021-08-25 00:17 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-25 00:50 UTC, merged